// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiCEggnrsdPpag73QUd0zn7kmmHc9heXI',
    appId: '1:634083829910:web:ba5d8bac45eb7811fd3ab7',
    messagingSenderId: '634083829910',
    projectId: 'notification-1ece1',
    authDomain: 'notification-1ece1.firebaseapp.com',
    storageBucket: 'notification-1ece1.firebasestorage.app',
    measurementId: 'G-0VJ35Y3E61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfbYC6YAtRpfD20wdOgHCA7pSdlb3HL0w',
    appId: '1:634083829910:android:a054c4348a58e27bfd3ab7',
    messagingSenderId: '634083829910',
    projectId: 'notification-1ece1',
    storageBucket: 'notification-1ece1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBts8zlIVW2ivELEPHfQ1Zm9EqUia4ZPA',
    appId: '1:634083829910:ios:fbfd2b2e06614553fd3ab7',
    messagingSenderId: '634083829910',
    projectId: 'notification-1ece1',
    storageBucket: 'notification-1ece1.firebasestorage.app',
    iosBundleId: 'com.example.notifikasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBts8zlIVW2ivELEPHfQ1Zm9EqUia4ZPA',
    appId: '1:634083829910:ios:fbfd2b2e06614553fd3ab7',
    messagingSenderId: '634083829910',
    projectId: 'notification-1ece1',
    storageBucket: 'notification-1ece1.firebasestorage.app',
    iosBundleId: 'com.example.notifikasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiCEggnrsdPpag73QUd0zn7kmmHc9heXI',
    appId: '1:634083829910:web:946a9f21e7402e5ffd3ab7',
    messagingSenderId: '634083829910',
    projectId: 'notification-1ece1',
    authDomain: 'notification-1ece1.firebaseapp.com',
    storageBucket: 'notification-1ece1.firebasestorage.app',
    measurementId: 'G-EKCWPD1E16',
  );
}
